"""adding honey pull

Revision ID: 43d060a7334a
Revises: 2798bf4af6f0
Create Date: 2025-01-31 14:41:43.048433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d060a7334a'
down_revision = '2798bf4af6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honey_pulls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('date_pulled', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], name=op.f('fk_honey_pulls_hive_id_hives')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('honey_pulls')
    # ### end Alembic commands ###
