"""adding events models

Revision ID: 72d4976745d9
Revises: eacd876dc06e
Create Date: 2025-01-29 11:58:34.323241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d4976745d9'
down_revision = 'eacd876dc06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanatory_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_name', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('is_explanatory', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('joblib_loc', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('descr', sa.String(length=500), nullable=True),
    sa.Column('zipcode', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_signup_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signup_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queen_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_inspections_hive_id_hives', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_inspections_queen_id_queens'), 'queens', ['queen_id'], ['id'])
        batch_op.drop_column('hive_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('zipcode')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hive_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_inspections_queen_id_queens'), type_='foreignkey')
        batch_op.create_foreign_key('fk_inspections_hive_id_hives', 'hives', ['hive_id'], ['id'])
        batch_op.drop_column('queen_id')

    op.drop_table('signup')
    op.drop_table('events')
    op.drop_table('model_history')
    op.drop_table('explanatory_variables')
    # ### end Alembic commands ###
