"""empty message

Revision ID: eacd876dc06e
Revises: 
Create Date: 2025-01-28 10:49:19.305387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacd876dc06e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_long', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hives_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('date_checked', sa.Date(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('activity_surrounding_hive', sa.String(length=50), nullable=True),
    sa.Column('super_count', sa.Integer(), nullable=True),
    sa.Column('hive_body_count', sa.Integer(), nullable=True),
    sa.Column('egg_count', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='countcategory'), nullable=True),
    sa.Column('larvae_count', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='countcategory'), nullable=True),
    sa.Column('capped_brood', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='countcategory'), nullable=True),
    sa.Column('twisted_larvae', sa.Boolean(), nullable=True),
    sa.Column('pests_surrounding', sa.String(length=50), nullable=True),
    sa.Column('stability_in_hive', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='countcategory'), nullable=True),
    sa.Column('feeding', sa.String(length=50), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('stores', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='countcategory'), nullable=True),
    sa.Column('fate', sa.String(length=50), nullable=True),
    sa.Column('local_bloom', sa.String(length=50), nullable=True),
    sa.Column('weather_conditions', sa.String(length=50), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('chalkbrood_presence', sa.Boolean(), nullable=True),
    sa.Column('varroa_mites', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], name=op.f('fk_inspections_hive_id_hives')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('date_introduced', sa.Date(), nullable=False),
    sa.Column('replacement_cause', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], name=op.f('fk_queens_hive_id_hives')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queens')
    op.drop_table('inspections')
    op.drop_table('hives')
    op.drop_table('users')
    # ### end Alembic commands ###
